name: gh-selfhost-runners

services:
  gha-runner1:
    build:
      context: .
      target: runner-build
      args:
        BASE_IMAGE: ghcr.io/jul-m/gha-runner-compose:u24.04-essentials-latest
        RUNNER_COMPONENTS: yq,docker
        # APT_PACKAGES: maven
    container_name: gha-runner1
    env_file:
      - .env
    environment:
      - RUNNER_NAME=gha-runner1
    volumes:
      - gha-runner1_data:/opt/actions-runner
    # privileged: true  # Enable only if your workflows run Docker inside the runner (DinD)

volumes:
  gha-runner1_data:

# Components matrix and arch support: see docs/components.md
