name: Test Runner Images
run-name: "Test Runner Images - ${{ github.event_name }} - #${{ github.run_number }}"

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, edited]

permissions:
  contents: read

jobs:
  # TEST BASE IMAGE
  build-test-base-image:
    name: Build and Test Base Image (${{ matrix.arch }})
    runs-on: ${{ matrix.host-runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            host-runner: ubuntu-24.04
          - arch: arm64
            host-runner: ubuntu-24.04-arm
    steps:
      - name: Build base image (${{ matrix.arch }})
        uses: ./.github/actions/test-runner-image
        with:
          image-tag: gha-runner-compose-base:test-${{ matrix.arch }}
          build-target: base
          runner-suffix: build-base-${{ matrix.arch }}
          cache-scope: base-${{ matrix.arch }}
          output-artifact-name: base-image-${{ matrix.arch }}
          test-job-name: ${{ format('Test Runner (base / {0})', matrix.arch) }}
          github-token: ${{ secrets.ACTION_GH_TOKEN }}

  test-base:
    name: Test Runner (base / ${{ matrix.arch }})
    runs-on: ${{ format('test-runner-base-{0}-{1}', matrix.arch, github.run_id) }}
    strategy:
      matrix:
        include:
          - arch: amd64
          - arch: arm64
    steps:
      - name: Run basic test
        run: |  # shell
          echo "Hello from self-hosted runner (base / ${{ matrix.arch }})!"
          echo "Runner is working correctly."


  # TEST ESSENTIALS IMAGE
  build-test-essentials-image:
    name: Build and Test Essentials Image (${{ matrix.arch }})
    runs-on: ${{ matrix.host-runner }}
    needs: build-test-base-image
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            host-runner: ubuntu-24.04
          - arch: arm64
            host-runner: ubuntu-24.04-arm
    steps:
      - name: Build essentials image (${{ matrix.arch }})
        uses: ./.github/actions/test-runner-image
        with:
          base-artifact-name: base-image-${{ matrix.arch }}
          image-tag: gha-runner-compose:essentials-test-${{ matrix.arch }}
          build-target: runner-build
          runner-suffix: build-essentials-${{ matrix.arch }}
          cache-scope: essentials-${{ matrix.arch }}
          runner-components: all-essentials
          additional-build-args: |
            BASE_IMAGE=gha-runner-compose-base:test-${{ matrix.arch }}
          output-artifact-name: essentials-image-${{ matrix.arch }}
          test-job-name: ${{ format('Test Runner (essentials / {0})', matrix.arch) }}
          github-token: ${{ secrets.ACTION_GH_TOKEN }}

  test-essentials:
    name: Test Runner (essentials / ${{ matrix.arch }})
    needs: build-test-base-image
    runs-on: ${{ format('test-runner-essentials-{0}-{1}', matrix.arch, github.run_id) }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
          - arch: arm64
    steps:
      - name: Run basic test
        run: |  # shell
          # Basic job test for essentials / ${{ matrix.arch }}
          echo "Hello from self-hosted runner (essentials / ${{ matrix.arch }})!"
          echo "Runner is working correctly."
          uname -a


  # TEST "BUILD" IMAGE
  build-test-build-runner:
    name: Start Runner (build / ${{ matrix.arch }})
    needs: build-test-essentials-image
    runs-on: ${{ matrix.host-runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            host-runner: ubuntu-24.04
          - arch: arm64
            host-runner: ubuntu-24.04-arm
    steps:
      - name: Validate "build" image (${{ matrix.arch }})
        uses: ./.github/actions/test-runner-image
        with:
          base-artifact-name: essentials-image-${{ matrix.arch }}
          image-tag: gha-runner-compose:build-test-${{ matrix.arch }}
          build-target: runner-build
          runner-suffix: ${{ format('build-{0}', matrix.arch) }}
          cache-scope: test-build-${{ matrix.arch }}
          runner-components: all-build
          test-job-name: ${{ format('Test Runner (build / {0})', matrix.arch) }}
          github-token: ${{ secrets.ACTION_GH_TOKEN }}

  test-build:
    name: Test Runner (build / ${{ matrix.arch }})
    needs: build-test-essentials-image
    runs-on: ${{ format('test-runner-build-{0}-{1}', matrix.arch, github.run_id) }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
          - arch: arm64
    steps:
      - name: Run basic test
        run: |  # shell
          # Basic job test for build / ${{ matrix.arch }}
          echo "Hello from self-hosted runner (build / ${{ matrix.arch }})!"
          echo "Runner is working correctly."
          uname -a