name: Test Runner Images
run-name: "Test Runner Images - ${{ github.event_name }} - #${{ github.run_number }}"

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, edited]

jobs:
  build-and-start-runner:
    name: Build and Start Runner Containers (${{ matrix.arch-suffix }})
    runs-on: ${{ matrix.host-runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - host-runner: ubuntu-24.04
            arch-suffix: amd64
          - host-runner: ubuntu-24.04-arm
            arch-suffix: arm64
    permissions:
      contents: read
      actions: write

    steps:
      - name: Test base image (${{ matrix.arch-suffix }})
        uses: ./.github/actions/test-runner-image
        with:
          image-tag: gha-runner-base:test
          build-target: base
          runner-suffix: base-${{ matrix.arch-suffix }}
          test-job-name: ${{ format('Test Container Runner (base / {0})', matrix.arch-suffix) }}
          gh-token: ${{ github.token }}
          github-token: ${{ github.token }}

      - name: Test essentials image (${{ matrix.arch-suffix }})
        uses: ./.github/actions/test-runner-image
        with:
          image-tag: gha-runner-essentials:test
          build-target: runner-build
          runner-suffix: essentials-${{ matrix.arch-suffix }}
          runner-components: all-essentials
          test-job-name: ${{ format('Test Container Runner (essentials / {0})', matrix.arch-suffix) }}
          gh-token: ${{ github.token }}
          github-token: ${{ github.token }}

  test-basic-job:
    name: Test Container Runner (${{ matrix.image-name }} / ${{ matrix.arch-suffix }})
    runs-on: ${{ format('test-runner-{0}-{1}', matrix.runner-suffix, github.run_id) }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image-name: base
            arch-suffix: amd64
            runner-suffix: base-amd64
          - image-name: essentials
            arch-suffix: amd64
            runner-suffix: essentials-amd64
          - image-name: base
            arch-suffix: arm64
            runner-suffix: base-arm64
          - image-name: essentials
            arch-suffix: arm64
            runner-suffix: essentials-arm64
    steps:
      - name: Run basic test
        run: |  # shell
          # Basic job test for ${{ matrix.image-name }} / ${{ matrix.arch-suffix }}
          echo "Hello from self-hosted runner (${{ matrix.image-name }} / ${{ matrix.arch-suffix }})!"
          echo "Runner is working correctly."
          uname -a