name: Test Base Image
run-name: "Test Base Image - ${{ github.event_name }} - #${{ github.run_number }}"

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, edited]

jobs:
  build-and-start-runner:
    name: Build and Start Runner Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          target: base
          tags: gha-runner-base:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify image was built
        run: |  # shell
          # Verify image was built
          docker image ls gha-runner-base:test
          docker image inspect gha-runner-base:test --format='{{json .}}' | jq '.RepoTags, .Size'

      - name: Start runner container
        env:
          GH_TOKEN: ${{ secrets.ACTION_GH_TOKEN }}
        run: |  # shell
          # Get runner registration token
          TOKEN=$(gh api --method POST "repos/${{ github.repository }}/actions/runners/registration-token" --jq .token)

          # Start runner container in background
          docker run -d --name test-runner \
            -e RUNNER_REPO_URL="${{ github.server_url }}/${{ github.repository }}" \
            -e RUNNER_TOKEN="$TOKEN" \
            -e RUNNER_NAME="test-runner-${{ github.run_id }}" \
            -e RUNNER_LABELS="test-base,test-runner-${{ github.run_id }}" \
            gha-runner-base:test

      - name: Wait for runner registration and execution
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |  # shell
          # Wait for runner registration and execution
          counter=0
          while true; do
            echo "Wait runner registration message in container logs..."

            # Check if container is still running
            if ! docker ps --format '{{.Names}}' | grep -q '^test-runner$'; then
              echo "❌ Runner container has stopped unexpectedly."
              echo "Runner logs:"
              docker logs test-runner 2>&1
              exit 1
            fi

            LOGS=$(docker logs test-runner 2>&1)
            if echo "$LOGS" | grep "Listening for Jobs"; then
              echo "✅ Runner registered successfully."
              break
            fi

            counter=$((counter + 1))
            if [ $counter -ge 30 ]; then
              echo "❌ Timeout waiting for runner to register."
              echo "Runner logs:"
              echo "$LOGS"
              exit 1
            fi

            sleep 10
          done
          
          # Wait for test-basic-job to complete successfully
          echo "Waiting for test-basic-job to complete..."
          counter=0
          while true; do
            JOB_STATUS=$(gh api "repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs" \
              --jq ".jobs[] | select(.name == \"Test Container Runner\") | .conclusion")
            echo "Current test-basic-job status: $JOB_STATUS"

            if [ "$JOB_STATUS" = "success" ]; then
              echo "✅ test-basic-job completed successfully."
              break
            elif [ "$JOB_STATUS" = "failure" ] || [ "$JOB_STATUS" = "cancelled" ] || [ "$JOB_STATUS" = "timed_out" ]; then
              echo "❌ test-basic-job failed with status: $JOB_STATUS"
              exit 1
            fi

            counter=$((counter + 1))
            if [ $counter -ge 30 ]; then
              echo "❌ Timeout waiting for test-basic-job to complete."
              exit 1
            fi

            sleep 10
          done

      - name: Cleanup runner
        if: always()
        env:
          GH_TOKEN: ${{ secrets.ACTION_GH_TOKEN }}
        run: |  # shell
          # Cleanup runner
          docker stop test-runner || true
          docker rm test-runner || true

          RUNNER_ID=$(gh api "repos/${{ github.repository }}/actions/runners" \
            --jq ".runners[] | select(.name == \"test-runner-${{ github.run_id }}\") | .id" 2>/dev/null || echo "")
          
          if [ -n "$RUNNER_ID" ]; then
            echo "Removing runner with ID: $RUNNER_ID"
            gh api --method DELETE "repos/${{ github.repository }}/actions/runners/$RUNNER_ID" 2>/dev/null || true
          else
            echo "Runner not found or not registered."
          fi

  test-basic-job:
    name: Test Container Runner
    runs-on: 'test-runner-${{ github.run_id }}'
    steps:
      - name: Run basic test
        run: |  # shell
          # Basic job test
          echo "Hello from self-hosted runner!"
          echo "Runner is working correctly."
          uname -a